### ISSUE TITLE
Can't resolve 'skatejs/esnext'

### ISSUE THREAD

**Issue by YashaswiMaharshi** [bonitasoft/preact-content-loader#7]
./node_modules/preact-content-loader/dist/index.js
Module not found: Can't resolve 'skatejs/esnext' in 'D:\ABC_BitBucket\node_modules\preact-content-loader\dist'

If I replace the /dist folder from your example folder its work fine

Please let me know how to solve this issue ?

**Comment by kontrollanten** [comment]
I'm experiencing the same problem. If I clone the repo, build and point `preact-content-loader` to my local version everything works fine. I'd guess this would be solved if you publish a new version of the package. Can this be done?

**Comment by tbouffard** [comment]
This project is no longer maintained, so closing the issue.
